trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  buildConfiguration: 'Release'
stages:
- stage: 'Test'
  jobs:
  - job: 'Intregration Test'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
  - job: 'RunLoadTests'
      displayName: 'Run load tests'
      pool:
        vmImage: 'ubuntu-20.04'
      variables:
      - group: Release
      steps:
      - script: |
          wget -c ftp.ps.pl/pub/apache/jmeter/binaries/apache-jmeter-$(jmeterVersion).tgz
          tar -xzf apache-jmeter-$(jmeterVersion).tgz
        displayName: 'Install Apache JMeter'
      - script: apache-jmeter-$(jmeterVersion)/bin/./jmeter -n -t LoadTest.jmx -o Results.xml -Jhostname=$(STAGING_HOSTNAME)
        displayName: 'Run Load tests'
      - script: |
          sudo apt-get update
          sudo apt-get install xsltproc
          xsltproc JMeter2JUnit.xsl Results.xml > JUnit.xml
        displayName: 'Transform JMeter output to JUnit'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: JUnit.xml
