name: Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run JMeter Action
        uses: ./
        with:
          testFilePath: LoadTest.jmx
          args: "http://51.144.188.249"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results.xml
          path: ./
